import {
  breadcrumbTrail,
  highlightOnHover,
  nodeInfoDisplayer,
  popUpOnHover,
  sunburst,
  zoomOnClick,
  colorSchemes,
} from 'vue-d3-sunburst';
import 'vue-d3-sunburst/dist/vue-d3-sunburst.css';
import { scaleOrdinal } from 'd3-scale';

const colorSchemesNames = Object.keys(colorSchemes).map((key) => ({
  value: key,
  text: colorSchemes[key].name,
}));

export default {
  name: 'LemurBrainOntology',
  components: {
    sunburst,
    nodeInfoDisplayer,
    breadcrumbTrail,
    highlightOnHover,
    zoomOnClick,
    popUpOnHover,
  },
  data() {
    return {
      ontology: [
        {
          id: 997,
          atlas_id: -1,
          ontology_id: 1,
          acronym: 'root',
          name: 'root',
          color_hex_triplet: 'FFFFFF',
          graph_order: 0,
          st_level: 'null',
          hemisphere_id: 3,
          parent_structure_id: 'null',
          children: [
            {
              id: 8,
              atlas_id: 0,
              ontology_id: 1,
              acronym: 'grey',
              name: 'Basic cell groups and regions',
              color_hex_triplet: 'BFDAE3',
              graph_order: 1,
              st_level: 'null',
              hemisphere_id: 3,
              parent_structure_id: 997,
              children: [
                {
                  id: 567,
                  atlas_id: 70,
                  ontology_id: 1,
                  acronym: 'CH',
                  name: 'Cerebrum',
                  color_hex_triplet: '7E605D',
                  graph_order: 2,
                  st_level: 'null',
                  hemisphere_id: 3,
                  parent_structure_id: 8,
                  children: [
                    {
                      id: 688,
                      atlas_id: 85,
                      ontology_id: 1,
                      acronym: 'CTX',
                      name: 'Cerebral cortex',
                      color_hex_triplet: 'FA7404',
                      graph_order: 3,
                      st_level: 'null',
                      hemisphere_id: 3,
                      parent_structure_id: 567,
                      children: [
                        {
                          id: 315,
                          atlas_id: 746,
                          ontology_id: 1,
                          acronym: 'Isocortex',
                          name: 'Isocortex',
                          color_hex_triplet: 'FACD04',
                          graph_order: 4,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 688,
                          children: [
                            {
                              id: 3159,
                              acronym: 'L1',
                              name: 'Layer1',
                              color_hex_triplet: '77FD89',
                              graph_order: 5,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [],
                            },
                            {
                              id: 3158,
                              acronym: 'L2&3',
                              name: 'Layer2&3',
                              color_hex_triplet: '589BFC',
                              graph_order: 5,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [],
                            },
                            {
                              id: 3157,
                              acronym: 'L4',
                              name: 'Layer4',
                              color_hex_triplet: '979AFC',
                              graph_order: 5,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [],
                            },
                            {
                              id: 3156,
                              acronym: 'L5',
                              name: 'Layer5',
                              color_hex_triplet: 'CF0C06',
                              graph_order: 5,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [],
                            },
                            {
                              id: 3155,
                              acronym: 'L6',
                              name: 'Layer6',
                              color_hex_triplet: '066AB0',
                              graph_order: 5,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [],
                            },
                            {
                              id: 322,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA1-3',
                              name: 'Area 1-3',
                              color_hex_triplet: 'F6F47F',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 3221,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA1-3L1',
                                  name: 'Area 1-3, Layer1',
                                  color_hex_triplet: 'F6F47F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 322,
                                  children: [],
                                },
                                {
                                  id: 3222,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA1-3L2/3',
                                  name: 'Area 1-3, Layer2/3',
                                  color_hex_triplet: 'F6F47F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 322,
                                  children: [],
                                },
                                {
                                  id: 3223,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA1-3L4',
                                  name: 'Area 1-3, Layer4',
                                  color_hex_triplet: 'F6F47F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 322,
                                  children: [],
                                },
                                {
                                  id: 3224,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA1-3L5',
                                  name: 'Area 1-3, Layer5',
                                  color_hex_triplet: 'F6F47F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 322,
                                  children: [],
                                },
                                {
                                  id: 3225,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA1-3L6',
                                  name: 'Area 1-3, Layer6',
                                  color_hex_triplet: 'F6F47F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 322,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 985,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA4',
                              name: 'Area 4',
                              color_hex_triplet: 'F7F070',
                              graph_order: 10,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 9851,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA4L1',
                                  name: 'Area 4, Layer1',
                                  color_hex_triplet: 'F7F070',
                                  graph_order: 10,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 985,
                                  children: [],
                                },
                                {
                                  id: 9852,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA4L2/3',
                                  name: 'Area 4, Layer2/3',
                                  color_hex_triplet: 'F7F070',
                                  graph_order: 10,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 985,
                                  children: [],
                                },
                                {
                                  id: 9853,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA4L4',
                                  name: 'Area 4, Layer4',
                                  color_hex_triplet: 'F7F070',
                                  graph_order: 10,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 985,
                                  children: [],
                                },
                                {
                                  id: 9854,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA4L5',
                                  name: 'Area 4, Layer5',
                                  color_hex_triplet: 'F7F070',
                                  graph_order: 10,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 985,
                                  children: [],
                                },
                                {
                                  id: 9855,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA4L6',
                                  name: 'Area 4, Layer6',
                                  color_hex_triplet: 'F7F070',
                                  graph_order: 10,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 985,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 993,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA6',
                              name: 'Area 6',
                              color_hex_triplet: 'F8E652',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 9931,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA6L1',
                                  name: 'Area 6, Layer1',
                                  color_hex_triplet: 'F8E652',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 993,
                                  children: [],
                                },
                                {
                                  id: 9932,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA6L2/3',
                                  name: 'Area 6, Layer2/3',
                                  color_hex_triplet: 'F8E652',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 993,
                                  children: [],
                                },
                                {
                                  id: 9933,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA6L4',
                                  name: 'Area 6, Layer4',
                                  color_hex_triplet: 'F8E652',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 993,
                                  children: [],
                                },
                                {
                                  id: 9934,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA6L5',
                                  name: 'Area 6, Layer5',
                                  color_hex_triplet: 'F8E652',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 993,
                                  children: [],
                                },
                                {
                                  id: 9935,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA6L6',
                                  name: 'Area 6, Layer6',
                                  color_hex_triplet: 'F8E652',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 993,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 184,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA8',
                              name: 'Area 8',
                              color_hex_triplet: 'F9DF3B',
                              graph_order: 5,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 1841,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA8L1',
                                  name: 'Area 8, Layer1',
                                  color_hex_triplet: 'F9DF3B',
                                  graph_order: 5,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 184,
                                  children: [],
                                },
                                {
                                  id: 1842,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA8L2/3',
                                  name: 'Area 8, Layer2/3',
                                  color_hex_triplet: 'F9DF3B',
                                  graph_order: 5,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 184,
                                  children: [],
                                },
                                {
                                  id: 1843,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA8L4',
                                  name: 'Area 8, Layer4',
                                  color_hex_triplet: 'F9DF3B',
                                  graph_order: 5,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 184,
                                  children: [],
                                },
                                {
                                  id: 1844,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA8L5',
                                  name: 'Area 8, Layer5',
                                  color_hex_triplet: 'F9DF3B',
                                  graph_order: 5,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 184,
                                  children: [],
                                },
                                {
                                  id: 1845,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA8L6',
                                  name: 'Area 8, Layer6',
                                  color_hex_triplet: 'F9DF3B',
                                  graph_order: 5,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 184,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 39,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA24',
                              name: 'Area 24',
                              color_hex_triplet: 'F9B916',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 391,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA24L1',
                                  name: 'Area 24, Layer1',
                                  color_hex_triplet: 'F9B916',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 39,
                                  children: [],
                                },
                                {
                                  id: 392,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA24L2/3',
                                  name: 'Area 24, Layer2/3',
                                  color_hex_triplet: 'F9B916',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 39,
                                  children: [],
                                },
                                {
                                  id: 393,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA24L4',
                                  name: 'Area 24, Layer4',
                                  color_hex_triplet: 'F9B916',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 39,
                                  children: [],
                                },
                                {
                                  id: 394,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA24L5',
                                  name: 'Area 24, Layer5',
                                  color_hex_triplet: 'F9B916',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 39,
                                  children: [],
                                },
                                {
                                  id: 395,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA24L6',
                                  name: 'Area 24, Layer6',
                                  color_hex_triplet: 'F9B916',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 39,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 972,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA25',
                              name: 'Area 25',
                              color_hex_triplet: 'F9B41B',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 9721,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA25L1',
                                  name: 'Area 25, Layer1',
                                  color_hex_triplet: 'F9B41B',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 972,
                                  children: [],
                                },
                                {
                                  id: 9722,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA25L2/3',
                                  name: 'Area 25, Layer2/3',
                                  color_hex_triplet: 'F9B41B',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 972,
                                  children: [],
                                },
                                {
                                  id: 9723,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA25L4',
                                  name: 'Area 25, Layer4',
                                  color_hex_triplet: 'F9B41B',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 972,
                                  children: [],
                                },
                                {
                                  id: 9724,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA25L5',
                                  name: 'Area 25, Layer5',
                                  color_hex_triplet: 'F9B41B',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 972,
                                  children: [],
                                },
                                {
                                  id: 9725,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA25L6',
                                  name: 'Area 25, Layer6',
                                  color_hex_triplet: 'F9B41B',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 972,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 378,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA5',
                              name: 'Area 5',
                              color_hex_triplet: 'F7EB61',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 3781,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA5L1',
                                  name: 'Area 5, Layer1',
                                  color_hex_triplet: 'F7EB61',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 378,
                                  children: [],
                                },
                                {
                                  id: 3782,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA5L2/3',
                                  name: 'Area 5, Layer2/3',
                                  color_hex_triplet: 'F7EB61',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 378,
                                  children: [],
                                },
                                {
                                  id: 3783,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA5L4',
                                  name: 'Area 5, Layer4',
                                  color_hex_triplet: 'F7EB61',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 378,
                                  children: [],
                                },
                                {
                                  id: 3784,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA5L5',
                                  name: 'Area 5, Layer5',
                                  color_hex_triplet: 'F7EB61',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 378,
                                  children: [],
                                },
                                {
                                  id: 3785,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA5L6',
                                  name: 'Area 5, Layer6',
                                  color_hex_triplet: 'F7EB61',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 378,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 22,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA7',
                              name: 'Area 7',
                              color_hex_triplet: 'F8E142',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 221,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA7L1',
                                  name: 'Area 7, Layer1',
                                  color_hex_triplet: 'F8E142',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 22,
                                  children: [],
                                },
                                {
                                  id: 222,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA7L2/3',
                                  name: 'Area 7, Layer2/3',
                                  color_hex_triplet: 'F8E142',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 22,
                                  children: [],
                                },
                                {
                                  id: 223,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA7L4',
                                  name: 'Area 7, Layer4',
                                  color_hex_triplet: 'F8E142',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 22,
                                  children: [],
                                },
                                {
                                  id: 224,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA7L5',
                                  name: 'Area 7, Layer5',
                                  color_hex_triplet: 'F8E142',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 22,
                                  children: [],
                                },
                                {
                                  id: 225,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA7L6',
                                  name: 'Area 7, Layer6',
                                  color_hex_triplet: 'F8E142',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 22,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 48,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA23',
                              name: 'Area 23',
                              color_hex_triplet: 'FABE12',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 481,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA23L1',
                                  name: 'Area 23, Layer1',
                                  color_hex_triplet: 'FABE12',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 48,
                                  children: [],
                                },
                                {
                                  id: 482,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA23L2/3',
                                  name: 'Area 23, Layer2/3',
                                  color_hex_triplet: 'FABE12',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 48,
                                  children: [],
                                },
                                {
                                  id: 483,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA23L4',
                                  name: 'Area 23, Layer4',
                                  color_hex_triplet: 'FABE12',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 48,
                                  children: [],
                                },
                                {
                                  id: 484,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA23L5',
                                  name: 'Area 23, Layer5',
                                  color_hex_triplet: 'FABE12',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 48,
                                  children: [],
                                },
                                {
                                  id: 485,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA23L6',
                                  name: 'Area 23, Layer6',
                                  color_hex_triplet: 'FABE12',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 48,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 836,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA20',
                              name: 'Area 20',
                              color_hex_triplet: 'FAD214',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 8361,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA20L1',
                                  name: 'Area 20, Layer1',
                                  color_hex_triplet: 'FAD214',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 836,
                                  children: [],
                                },
                                {
                                  id: 8362,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA20L2/3',
                                  name: 'Area 20, Layer2/3',
                                  color_hex_triplet: 'FAD214',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 836,
                                  children: [],
                                },
                                {
                                  id: 8363,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA20L4',
                                  name: 'Area 20, Layer4',
                                  color_hex_triplet: 'FAD214',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 836,
                                  children: [],
                                },
                                {
                                  id: 8364,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA20L5',
                                  name: 'Area 20, Layer5',
                                  color_hex_triplet: 'FAD214',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 836,
                                  children: [],
                                },
                                {
                                  id: 8365,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA20L6',
                                  name: 'Area 20, Layer6',
                                  color_hex_triplet: 'FAD214',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 836,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 895,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA21',
                              name: 'Area 21',
                              color_hex_triplet: 'FAC809',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 8951,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA21L1',
                                  name: 'Area 21, Layer1',
                                  color_hex_triplet: 'FAC809',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 895,
                                  children: [],
                                },
                                {
                                  id: 8952,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA21L2/3',
                                  name: 'Area 21, Layer2/3',
                                  color_hex_triplet: 'FAC809',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 895,
                                  children: [],
                                },
                                {
                                  id: 8953,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA21L4',
                                  name: 'Area 21, Layer4',
                                  color_hex_triplet: 'FAC809',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 895,
                                  children: [],
                                },
                                {
                                  id: 8954,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA21L5',
                                  name: 'Area 21, Layer5',
                                  color_hex_triplet: 'FAC809',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 895,
                                  children: [],
                                },
                                {
                                  id: 8955,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA21L6',
                                  name: 'Area 21, Layer6',
                                  color_hex_triplet: 'FAC809',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 895,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 96,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA22',
                              name: 'Area 22',
                              color_hex_triplet: 'FAC30D',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 961,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA22L1',
                                  name: 'Area 22, Layer1',
                                  color_hex_triplet: 'FAC30D',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 96,
                                  children: [],
                                },
                                {
                                  id: 962,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA22L2/3',
                                  name: 'Area 22, Layer2/3',
                                  color_hex_triplet: 'FAC30D',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 96,
                                  children: [],
                                },
                                {
                                  id: 963,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA22L4',
                                  name: 'Area 22, Layer4',
                                  color_hex_triplet: 'FAC30D',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 96,
                                  children: [],
                                },
                                {
                                  id: 964,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA22L5',
                                  name: 'Area 22, Layer5',
                                  color_hex_triplet: 'FAC30D',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 96,
                                  children: [],
                                },
                                {
                                  id: 965,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA22L6',
                                  name: 'Area 22, Layer6',
                                  color_hex_triplet: 'FAC30D',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 96,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 1084,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA27',
                              name: 'Area 27',
                              color_hex_triplet: 'F9AF1F',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 10841,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA27L1',
                                  name: 'Area 27, Layer1',
                                  color_hex_triplet: 'F9AF1F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 1084,
                                  children: [],
                                },
                                {
                                  id: 10842,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA27L2/3',
                                  name: 'Area 27, Layer2/3',
                                  color_hex_triplet: 'F9AF1F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 1084,
                                  children: [],
                                },
                                {
                                  id: 10843,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA27L4',
                                  name: 'Area 27, Layer4',
                                  color_hex_triplet: 'F9AF1F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 1084,
                                  children: [],
                                },
                                {
                                  id: 10844,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA27L5',
                                  name: 'Area 27, Layer5',
                                  color_hex_triplet: 'F9AF1F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 1084,
                                  children: [],
                                },
                                {
                                  id: 10845,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA27L6',
                                  name: 'Area 27, Layer6',
                                  color_hex_triplet: 'F9AF1F',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 1084,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 909,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA28',
                              name: 'Area 28',
                              color_hex_triplet: 'F9AD21',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 9091,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA28L1',
                                  name: 'Area 28, Layer1',
                                  color_hex_triplet: 'F9AD21',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 909,
                                  children: [],
                                },
                                {
                                  id: 9092,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA28L2/3',
                                  name: 'Area 28, Layer2/3',
                                  color_hex_triplet: 'F9AD21',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 909,
                                  children: [],
                                },
                                {
                                  id: 9093,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA28L4',
                                  name: 'Area 28, Layer4',
                                  color_hex_triplet: 'F9AD21',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 909,
                                  children: [],
                                },
                                {
                                  id: 9094,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA28L5',
                                  name: 'Area 28, Layer5',
                                  color_hex_triplet: 'F9AD21',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 909,
                                  children: [],
                                },
                                {
                                  id: 9095,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA28L6',
                                  name: 'Area 28, Layer6',
                                  color_hex_triplet: 'F9AD21',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 909,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 385,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA17',
                              name: 'Area 17',
                              color_hex_triplet: 'F9D723',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 3851,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA17L1',
                                  name: 'Area 17, Layer1',
                                  color_hex_triplet: 'F9D723',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 385,
                                  children: [],
                                },
                                {
                                  id: 3852,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA17L2/3',
                                  name: 'Area 17, Layer2/3',
                                  color_hex_triplet: 'F9D723',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 385,
                                  children: [],
                                },
                                {
                                  id: 3853,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA17L4',
                                  name: 'Area 17, Layer4',
                                  color_hex_triplet: 'F9D723',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 385,
                                  children: [],
                                },
                                {
                                  id: 3854,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA17L5',
                                  name: 'Area 17, Layer5',
                                  color_hex_triplet: 'F9D723',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 385,
                                  children: [],
                                },
                                {
                                  id: 3855,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA17L6',
                                  name: 'Area 17, Layer6',
                                  color_hex_triplet: 'F9D723',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 385,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 669,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA18',
                              name: 'Area 18',
                              color_hex_triplet: 'FAD418',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 6691,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA18L1',
                                  name: 'Area 18, Layer1',
                                  color_hex_triplet: 'FAD418',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 669,
                                  children: [],
                                },
                                {
                                  id: 6692,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA18L2/3',
                                  name: 'Area 18, Layer2/3',
                                  color_hex_triplet: 'FAD418',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 669,
                                  children: [],
                                },
                                {
                                  id: 6693,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA18L4',
                                  name: 'Area 18, Layer4',
                                  color_hex_triplet: 'FAD418',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 669,
                                  children: [],
                                },
                                {
                                  id: 6694,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA18L5',
                                  name: 'Area 18, Layer5',
                                  color_hex_triplet: 'FAD418',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 669,
                                  children: [],
                                },
                                {
                                  id: 6695,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA18L6',
                                  name: 'Area 18, Layer6',
                                  color_hex_triplet: 'FAD418',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 669,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 95,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA13-16',
                              name: 'Area 13-16',
                              color_hex_triplet: 'F9DC33',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 951,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA13-16L1',
                                  name: 'Area 13-16, Layer1',
                                  color_hex_triplet: 'F9DC33',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 95,
                                  children: [],
                                },
                                {
                                  id: 952,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA13-16L2/3',
                                  name: 'Area 13-16, Layer2/3',
                                  color_hex_triplet: 'F9DC33',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 95,
                                  children: [],
                                },
                                {
                                  id: 953,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA13-16L4',
                                  name: 'Area 13-16, Layer4',
                                  color_hex_triplet: 'F9DC33',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 95,
                                  children: [],
                                },
                                {
                                  id: 954,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA13-16L5',
                                  name: 'Area 13-16, Layer5',
                                  color_hex_triplet: 'F9DC33',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 95,
                                  children: [],
                                },
                                {
                                  id: 955,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA13-16L6',
                                  name: 'Area 13-16, Layer6',
                                  color_hex_triplet: 'F9DC33',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 95,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 894,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA26-29',
                              name: 'Area 26-29',
                              color_hex_triplet: 'F9AA23',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 8941,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA26-29L1',
                                  name: 'Area 26-29, Layer1',
                                  color_hex_triplet: 'F9AA23',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 894,
                                  children: [],
                                },
                                {
                                  id: 8942,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA26-29L2/3',
                                  name: 'Area 26-29, Layer2/3',
                                  color_hex_triplet: 'F9AA23',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 894,
                                  children: [],
                                },
                                {
                                  id: 8943,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA26-29L4',
                                  name: 'Area 26-29, Layer4',
                                  color_hex_triplet: 'F9AA23',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 894,
                                  children: [],
                                },
                                {
                                  id: 8944,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA26-29L5',
                                  name: 'Area 26-29, Layer5',
                                  color_hex_triplet: 'F9AA23',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 894,
                                  children: [],
                                },
                                {
                                  id: 8945,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA26-29L6',
                                  name: 'Area 26-29, Layer6',
                                  color_hex_triplet: 'F9AA23',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 894,
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: 254,
                              atlas_id: 746,
                              ontology_id: 1,
                              acronym: 'BA30',
                              name: 'Area 03',
                              color_hex_triplet: 'F8A427',
                              graph_order: 15,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 315,
                              children: [
                                {
                                  id: 2541,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA30L1',
                                  name: 'Area 03, Layer1',
                                  color_hex_triplet: 'F8A427',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 254,
                                  children: [],
                                },
                                {
                                  id: 2542,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA30L2/3',
                                  name: 'Area 03, Layer2/3',
                                  color_hex_triplet: 'F8A427',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 254,
                                  children: [],
                                },
                                {
                                  id: 2543,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA30L4',
                                  name: 'Area 03, Layer4',
                                  color_hex_triplet: 'F8A427',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 254,
                                  children: [],
                                },
                                {
                                  id: 2544,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA30L5',
                                  name: 'Area 03, Layer5',
                                  color_hex_triplet: 'F8A427',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 254,
                                  children: [],
                                },
                                {
                                  id: 2545,
                                  atlas_id: 746,
                                  ontology_id: 1,
                                  acronym: 'BA30L6',
                                  name: 'Area 03, Layer6',
                                  color_hex_triplet: 'F8A427',
                                  graph_order: 15,
                                  st_level: 'null',
                                  hemisphere_id: 3,
                                  parent_structure_id: 254,
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: 3111,
                          atlas_id: 746,
                          ontology_id: 1,
                          acronym: 'R',
                          name: 'Remaining region',
                          color_hex_triplet: '965251',
                          graph_order: 5,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 688,
                          children: [],
                        },
                      ],
                    },
                    {
                      id: 1089,
                      atlas_id: 135,
                      ontology_id: 1,
                      acronym: 'HPF',
                      name: 'Hippocampal formation',
                      color_hex_triplet: '5DFA04',
                      graph_order: 415,
                      st_level: 'null',
                      hemisphere_id: 3,
                      parent_structure_id: 567,
                      children: [
                        {
                          id: 1929,
                          atlas_id: 135,
                          ontology_id: 1,
                          acronym: 'Er',
                          name: 'Regio Entorhinalis',
                          color_hex_triplet: 'FA8FF3',
                          graph_order: 415,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1089,
                          children: [],
                        },
                        {
                          id: 1939,
                          atlas_id: 135,
                          ontology_id: 1,
                          acronym: 'CA',
                          name: "Ammon's horn",
                          color_hex_triplet: 'EFFB72',
                          graph_order: 415,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1089,
                          children: [],
                        },
                        {
                          id: 1949,
                          atlas_id: 135,
                          ontology_id: 1,
                          acronym: 'DG',
                          name: 'Dentate Gyrus',
                          color_hex_triplet: 'FBA672',
                          graph_order: 415,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1089,
                          children: [],
                        },
                        {
                          id: 1959,
                          atlas_id: 135,
                          ontology_id: 1,
                          acronym: 'S',
                          name: 'Subiculum',
                          color_hex_triplet: '95FB72',
                          graph_order: 415,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1089,
                          children: [],
                        },
                        {
                          id: 1969,
                          atlas_id: 135,
                          ontology_id: 1,
                          acronym: 'Prs',
                          name: 'Presubiculum',
                          color_hex_triplet: 'FB72A2',
                          graph_order: 415,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1089,
                          children: [],
                        },
                        {
                          id: 1979,
                          atlas_id: 135,
                          ontology_id: 1,
                          acronym: 'IG',
                          name: 'Indusium Griseum',
                          color_hex_triplet: '5358FC',
                          graph_order: 415,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1089,
                          children: [],
                        },
                      ],
                    },
                    {
                      id: 623,
                      atlas_id: 77,
                      ontology_id: 1,
                      acronym: 'CNU',
                      name: 'Cerebral nuclei',
                      color_hex_triplet: '04FAEF',
                      graph_order: 520,
                      st_level: 'null',
                      hemisphere_id: 3,
                      parent_structure_id: 567,
                      children: [
                        {
                          id: 477,
                          atlas_id: 342,
                          ontology_id: 1,
                          acronym: 'STR',
                          name: 'Striatum',
                          color_hex_triplet: '04B7FA',
                          graph_order: 521,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 623,
                          children: [
                            {
                              id: 4779,
                              atlas_id: 342,
                              ontology_id: 1,
                              acronym: 'Cd',
                              name: 'Caudate Nucleus',
                              color_hex_triplet: '088F93',
                              graph_order: 521,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 477,
                              children: [],
                            },
                            {
                              id: 4778,
                              atlas_id: 342,
                              ontology_id: 1,
                              acronym: 'Put',
                              name: 'Putamen',
                              color_hex_triplet: '06985A',
                              graph_order: 521,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 477,
                              children: [],
                            },
                          ],
                        },
                        {
                          id: 803,
                          atlas_id: 241,
                          ontology_id: 1,
                          acronym: 'PAL',
                          name: 'Pallidum',
                          color_hex_triplet: '0440FA',
                          graph_order: 557,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 623,
                          children: [
                            {
                              id: 4777,
                              atlas_id: 342,
                              ontology_id: 1,
                              acronym: 'GPe',
                              name: 'Globus Pallidus, external segment',
                              color_hex_triplet: 'F69256',
                              graph_order: 521,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 803,
                              children: [],
                            },
                            {
                              id: 4776,
                              atlas_id: 342,
                              ontology_id: 1,
                              acronym: 'GPi',
                              name: 'Globus Pallidus, internal segment',
                              color_hex_triplet: '6C5B72',
                              graph_order: 521,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 803,
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 343,
                  atlas_id: 42,
                  ontology_id: 1,
                  acronym: 'BS',
                  name: 'Brain stem',
                  color_hex_triplet: 'FF7080',
                  graph_order: 588,
                  st_level: 'null',
                  hemisphere_id: 3,
                  parent_structure_id: 8,
                  children: [
                    {
                      id: 1129,
                      atlas_id: 140,
                      ontology_id: 1,
                      acronym: 'IB',
                      name: 'Interbrain',
                      color_hex_triplet: 'FF7080',
                      graph_order: 589,
                      st_level: 'null',
                      hemisphere_id: 3,
                      parent_structure_id: 343,
                      children: [
                        {
                          id: 549,
                          atlas_id: 351,
                          ontology_id: 1,
                          acronym: 'TH',
                          name: 'Thalamus',
                          color_hex_triplet: '5A04FA',
                          graph_order: 590,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1129,
                          children: [],
                        },
                        {
                          id: 1097,
                          atlas_id: 136,
                          ontology_id: 1,
                          acronym: 'HY',
                          name: 'Hypothalamus',
                          color_hex_triplet: 'E64438',
                          graph_order: 655,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1129,
                          children: [
                            {
                              id: 4775,
                              atlas_id: 342,
                              ontology_id: 1,
                              acronym: 'STN',
                              name: 'Subthalamic Nucleus',
                              color_hex_triplet: '0F7E32',
                              graph_order: 521,
                              st_level: 'null',
                              hemisphere_id: 3,
                              parent_structure_id: 1097,
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: 313,
                      atlas_id: 180,
                      ontology_id: 1,
                      acronym: 'MB',
                      name: 'Midbrain',
                      color_hex_triplet: 'AF04FA',
                      graph_order: 740,
                      st_level: 'null',
                      hemisphere_id: 3,
                      parent_structure_id: 343,
                      children: [
                        {
                          id: 4774,
                          atlas_id: 342,
                          ontology_id: 1,
                          acronym: 'SNc',
                          name: 'Substantia nigra, compact part',
                          color_hex_triplet: 'FC9D95',
                          graph_order: 521,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 313,
                          children: [],
                        },
                        {
                          id: 4773,
                          atlas_id: 342,
                          ontology_id: 1,
                          acronym: 'SNr',
                          name: 'Substantia nigra, reticular part',
                          color_hex_triplet: 'FE4365',
                          graph_order: 521,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 313,
                          children: [],
                        },
                      ],
                    },
                    {
                      id: 1065,
                      atlas_id: 132,
                      ontology_id: 1,
                      acronym: 'HB',
                      name: 'Hindbrain',
                      color_hex_triplet: 'EF04FA',
                      graph_order: 801,
                      st_level: 'null',
                      hemisphere_id: 3,
                      parent_structure_id: 343,
                      children: [
                        {
                          id: 771,
                          atlas_id: 237,
                          ontology_id: 1,
                          acronym: 'P',
                          name: 'Pons',
                          color_hex_triplet: 'FA04AF',
                          graph_order: 802,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1065,
                          children: [],
                        },
                        {
                          id: 354,
                          atlas_id: 185,
                          ontology_id: 1,
                          acronym: 'MY',
                          name: 'Medulla',
                          color_hex_triplet: 'FA0465',
                          graph_order: 849,
                          st_level: 'null',
                          hemisphere_id: 3,
                          parent_structure_id: 1065,
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 512,
                  atlas_id: 63,
                  ontology_id: 1,
                  acronym: 'CB',
                  name: 'Cerebellum',
                  color_hex_triplet: 'FA0422',
                  graph_order: 927,
                  st_level: 'null',
                  hemisphere_id: 3,
                  parent_structure_id: 8,
                  children: [],
                },
              ],
            },
            {
              id: 1009,
              atlas_id: 691,
              ontology_id: 1,
              acronym: 'FT',
              name: 'fiber tracts',
              color_hex_triplet: 'A9B00A',
              graph_order: 1013,
              st_level: 'null',
              hemisphere_id: 3,
              parent_structure_id: 997,
              children: [],
            },
            {
              id: 73,
              atlas_id: 716,
              ontology_id: 1,
              acronym: 'VS',
              name: 'ventricular systems',
              color_hex_triplet: 'F58355',
              graph_order: 1199,
              st_level: 'null',
              hemisphere_id: 3,
              parent_structure_id: 997,
              children: [
                {
                  id: 9101,
                  atlas_id: 716,
                  ontology_id: 1,
                  acronym: 'V1',
                  name: 'lateral ventricle',
                  color_hex_triplet: '046F12',
                  graph_order: 1199,
                  st_level: 'null',
                  hemisphere_id: 3,
                  parent_structure_id: 73,
                  children: [],
                },
                {
                  id: 9102,
                  atlas_id: 716,
                  ontology_id: 1,
                  acronym: 'V3',
                  name: 'third ventricle',
                  color_hex_triplet: '97FEE8',
                  graph_order: 1199,
                  st_level: 'null',
                  hemisphere_id: 3,
                  parent_structure_id: 73,
                  children: [],
                },
                {
                  id: 9103,
                  atlas_id: 716,
                  ontology_id: 1,
                  acronym: 'V4',
                  name: 'fourth ventricle',
                  color_hex_triplet: 'FD79AB',
                  graph_order: 1199,
                  st_level: 'null',
                  hemisphere_id: 3,
                  parent_structure_id: 73,
                  children: [],
                },
              ],
            },
          ],
        },
      ],
      open: [1, 2],
      search: null,
      caseSensitive: false,
      tree: {
        name: 'root',
        children: [
          {
            name: 'Basic cell groups and regions',
            children: [
              {
                name: 'Cerebrum',
                children: [
                  {
                    name: 'Cerebral cortex',
                    children: [
                      {
                        name: 'Isocortex',
                        size: 226364520,
                      },
                      {
                        name: 'Remaining region',
                        size: 28221982,
                      },
                    ],
                  },
                  {
                    name: 'Hippocampal formation',
                    size: 47944705,
                  },
                  {
                    name: 'Cerebral nuclei',
                    children: [
                      {
                        name: 'Striatum',
                        size: 36610559,
                      },
                      {
                        name: 'Pallidum',
                        size: 10201870,
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Brain stem',
                children: [
                  {
                    name: 'Interbrain',
                    children: [
                      {
                        name: 'Thalamus',
                        size: 28885093,
                      },
                      {
                        name: 'Hypothalamus',
                        size: 10415044,
                      },
                    ],
                  },
                  {
                    name: 'Midbrain',
                    size: 35585278,
                  },
                  {
                    name: 'Hindbrain',
                    children: [
                      {
                        name: 'Pons',
                        size: 11466405,
                      },
                      {
                        name: 'Medulla',
                        size: 28672448,
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Cerebellum',
                size: 64319042,
              },
            ],
          },
          {
            name: 'fiber tracts',
            size: 52953042,
          },
          {
            name: 'ventricular systems',
            size: 4974184,
          },
        ],
      },
      minAngleDisplayed: 0.01,
      colorScheme: colorSchemesNames[0].value,
      colorSchemes: colorSchemesNames,
      inAnimationDuration: 100,
      outAnimationDuration: 1000,
      overrideColorScale: false,
      centralCircleRelativeSize: 25,
      showLabels: true,
      showLabelsOptions: [
        { text: 'false', value: false },
        { text: 'true', value: true },
        { text: 'custom', value: this.showLabelsFunction },
      ],
      custoColorScale: scaleOrdinal([
        '#e39b89',
        '#31ea74',
        '#3c7227',
        '#9dad1f',
      ]),
    };
  },
  computed: {
    colorScale() {
      return this.overrideColorScale ? this.custoColorScale : null;
    },
    filter() {
      return this.caseSensitive
        ? (item, search, textKey) => item[textKey].indexOf(search) > -1
        : undefined;
    },
  },
  methods: {
    showLabelsFunction(d) {
      const {
        data1,
        context: { angle, relativeDepth },
      } = d;
      if (relativeDepth > 2 || angle < 5) {
        return null;
      }
      return data1.name;
    },
  },
};
